sudo: true
notifications:
  slack:
    rooms:
      secure: HmuBbaRMwsLkC305vZCl+I65FBJvFjbATPJOIcwKBb6qp0ZKeol4R05W1WgGw809ARE2FnLZD32IwIO5lS6rEJPGU7eMVTrej9VaPpHEb3z14PxIsTh/pkVg+EZF6tgxpyqJ5+55/KZqz6LsiCdGpehEaAdtqvczFfqaGN46/Gnbjym11IzVqjYdKo6oHNCg5Wpr4Flnx9cLU4kLdPunuKfbmHRyxx1WblXJ4YLKMT1NaUixyOnYqlDRGm/VU3pY5wOA+f+XrqcGuR/TDjAFRe613IcpjRPn5AsNypIoA60CP+DjokSMufRr27FObjo3JhQW6ykKxOurjf8NhV+lvwbVWd+kzuajCsQoTilQYyQXEcj2aaidZIZRSnYK9l07996qcfcQ8/+s6SIX7U3udncousdj81qIcfL9TnyaZnpiqjIYNEsTN3wmfEfVSEXf746tbDD2PBwxQACa7nXzA96uDxO24ou2wdPbo8c2sfsBBlKkhTK98tchqQjdHs1uA+c4+T0XHxUGzQLVRo/ynDXwnb7TVCbuG0OSFRTJvez8ZzMilddZs6dush0/JRclQEQa4l7/50dRLooHcsL7QYCMS2AzU25aEkqGl64uD3djVbHnAATyKVOswDddCwGEvEWG4JzR15gYXFQGvlzopfp7r5nVI9vAMtu2Tc6qf1k=
    on_success: never
    on_failure: always

env:
  global:
  - secure: QAWiAr6jeHg68ymgdAf45F+hi+raOfclzNnzeTB9UNvYD+uS13TyaAsUkZz5WA2CcKIoA/a854bT1+CyTKz1IEXJBAs75Kf5kYWFzFHZFGgwzHIrNXzUA4Oj0yXeyu/3Ut9/+qjpNdvi4hGPLodkdQc42Qq+w+LCgytXWoThk//K1tY3uEZN7CnSXzU4uXflnHNQMb5/QQ+PmajpCVLfqv/Y1XoFr1iERVYo64Mmiw9NcqrgtmWAhVBq3jcLi2pwTKe09SKqhJA4AAgrLlNcJIsTlz2KFOhU3LNsj49mB+HSEWJBSF/qtygBaNtA8CF/BgRRFTBU+tzDBqCj7BJPOmfVcvpyhLH3O/Ve2EoBJ8iiBszNJvQDAgTTfHYjxFyVZtirtNbgDlwZRtcyAH7rZgsl7jHHRbRwoNc2cM7K1OYF3m6qoGFl80A13U/8IarIlfFeqtQNpjsNWPQP0g47xDAUDxB7SMOPLVc1KiIDHQzBGB10/XlZLwomB0wznv7ulpBhDMUuDUW8PtydI0oj8UTOnqHLxllWKrqbXvyrTT9qRwAbl2C9PRYzdMIUGmf0wcg56VTdzpg/83Mih+1Xm1nmXUMot06bXuKxMphraf4cI3xSjevD/jM16ubW1WU7hdLSL1I691Dli2zTrMF9s2b+5MmRO3O5VNyCSsZ7BcQ=
  - secure: iBo7KW99OofackgKUVAVSMdTEz7jaxue/Gkjyofm7yVbJNDECCUsndLYQFn5lUvgL6eXY02EFLEDk/QyMbDPigXKf5z0rPlk6wbiomYst22PbOj+cbM2gi+cag8kyrMuNbJfpfjC1PG3JjgkmRxarnu7ru7+zbZbeGWaWmV2y/JungZSaMWTwbaiyEP0UQQ/Mf4QtS2SBgBdfqvnR4QdauIK+cA27CD8muNUx0jKV/4N3UgVWxAV0XCdQo5oyttNgbsJwaaDduWhuZ/iFRtSNhszaPMvYmXAGBbzjD5pE0KZwUlauUO0pYKZsDDscb+cRnscDbckwJVpSyVWd0iz9uTrPtrmUzY/Eqv7dbyp+9GqWODWi9721DmF5BHTVf+GqUYN3y6MLWffKPgtaoBdV0Fbp/4OK47CyzODmF/0DKnLl/cTQH6K9/cCgqWk0f5HgPSLi65byeWH59IAKsLpgXGwOLSNega9qu4oIu6uTFJ3McMmFaPCv6z9Jlvx8TmAdYfKPej+D+843On2JGQnqdUhtYpzS4BlB8p22C8BBA+cjemWtnkGsDUEDbqyTG9RU00VE0xCSnF7jc90KstiQ7sRQBh9j9U/+CoAY4rkw8f8pjsgH15KdFdeyw9Cp7Xl8r/Q80hwTa7Z3BGfv+TMbD2PhQ3FGBbBazOKOrndJo0=
  - REPOSITORY_URI_DEVELOP=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-develop
  - REPOSITORY_URI_STAGING=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-staging
  - REPOSITORY_DEMO_URI_DEVELOP=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-develop
  - REPOSITORY_DEMO_URI_STAGING=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-staging
  - IMAGE_TAG=$TRAVIS_COMMIT

branches:
  only:
  - master
  - develop
language: node_js
node_js:
- '12'

cache:
  yarn: true

services:
- docker

install:
- yarn

before_script:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - echo Logging in to Amazon...
  - aws --version
  - "$(aws ecr get-login --region us-east-2 --no-include-email)"
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then sh scripts/load-dependencies.sh dev; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sh scripts/load-dependencies.sh staging; fi

script:
  - yarn lint
  - yarn test:ci
  - yarn build
  - docker build -t ownid-client-app:latest .

  - yarn build:demo
  - cd projects/demo-app && docker build -t ownid-demo-app:latest .

before_deploy:
  - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv kubectl /usr/local/bin
  - kubectl version --short --client
  - aws eks --region us-east-2 update-kubeconfig --name ownid-eks

deploy:
- provider: script
  script: sh scripts/deploy.sh $REPOSITORY_URI_DEVELOP $REPOSITORY_DEMO_URI_DEVELOP $IMAGE_TAG dev
  on:
    branch: develop
- provider: script
  script: sh scripts/deploy.sh $REPOSITORY_URI_STAGING $REPOSITORY_DEMO_URI_STAGING $IMAGE_TAG staging
  on:
    branch: master
