sudo: true
notifications:
  slack:
    rooms:
      secure: HmuBbaRMwsLkC305vZCl+I65FBJvFjbATPJOIcwKBb6qp0ZKeol4R05W1WgGw809ARE2FnLZD32IwIO5lS6rEJPGU7eMVTrej9VaPpHEb3z14PxIsTh/pkVg+EZF6tgxpyqJ5+55/KZqz6LsiCdGpehEaAdtqvczFfqaGN46/Gnbjym11IzVqjYdKo6oHNCg5Wpr4Flnx9cLU4kLdPunuKfbmHRyxx1WblXJ4YLKMT1NaUixyOnYqlDRGm/VU3pY5wOA+f+XrqcGuR/TDjAFRe613IcpjRPn5AsNypIoA60CP+DjokSMufRr27FObjo3JhQW6ykKxOurjf8NhV+lvwbVWd+kzuajCsQoTilQYyQXEcj2aaidZIZRSnYK9l07996qcfcQ8/+s6SIX7U3udncousdj81qIcfL9TnyaZnpiqjIYNEsTN3wmfEfVSEXf746tbDD2PBwxQACa7nXzA96uDxO24ou2wdPbo8c2sfsBBlKkhTK98tchqQjdHs1uA+c4+T0XHxUGzQLVRo/ynDXwnb7TVCbuG0OSFRTJvez8ZzMilddZs6dush0/JRclQEQa4l7/50dRLooHcsL7QYCMS2AzU25aEkqGl64uD3djVbHnAATyKVOswDddCwGEvEWG4JzR15gYXFQGvlzopfp7r5nVI9vAMtu2Tc6qf1k=
    on_success: never
    on_failure: always

language: node_js
node_js:
  - '12'

services:
  - docker

cache:
  yarn: true

env:
  global:
    - secure: NDtY1i1VYxMeopm1Dh1EP8Znps/rPgEwNLAwOefoQPB1BbbqZYQA0IjBM5ArDz25MSh5OSFumWb5MBZ71FsKE5oBLjWnAWXqzWj8jiNGfWtsg+DENCXTaPD7pF6YHppWpucodvGi6QAzFaYC7gIG3xrj89kJvAW+DiK7JFxBmvbAMGhI5G/JrOwreTHlbmFjiNj6q+x8R85/GRxB7SOHuwf5kdsylKsFrolyYsDhYe98pH422alH10RSPYJyVler6K3rOLjDlNWxzYPOu4z2V6AV49SG8F/u7gbOuvl9gB9IpwzsWv4O11CmFrz0d3Y/CzF0LBD2NXrD1bq3d+sphir03KOBb9kcm/jPPSk0jlU5B2cDZbOXWRwI3NFYNavPtnscIx2TQwybDdF0snqFD+qWHqnc2JcBqtmdnrYu+wHzreFcrpmdHwfDlJOgQZS2EExief2mux0QkEtdx0bgizb1uOFApYOI44XvKhMwInTculrqwbGDvirPLlNSUDCnveMkkRHtWkMwYenW5GGKwPSwIWsTUQjExuNRlaAEbOp2SyaUcHkmxdb+Jv7HS5HGyxSJ63kV5hmIHO20t5rbs+VqcObAzqXL7ro6S4kwzrpXebY97VgiJhb/Gal86W7AA+eHOf6BKQPYXwL+gurJHwnQeuSb5VvL2TRhVeRxcx4=
    - IMAGE_TAG=$TRAVIS_COMMIT


branches:
  only:
  - master
  - develop
  - /^release\/([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])).*$/

jobs:
  include:
    - if: branch = master
      env: 
        ENV=staging 
        GIGYA_DEMO=3_O4QE0Kk7QstG4VGDPED5omrr8mgbTuf_Gim8V_Y19YDP75m_msuGtNGQz89X0KWP
        GIGYA_DEMO_2=3_uQMbdn-ceccHKTdOmcCqrTDsGq3e7anDWcAxm2g4jFdE63dTpv1S8NCKy_sf_eEA
    - if: branch = develop
      env: 
        ENV=dev 
        GIGYA_DEMO=3_hOdIVleWrXNvjArcZRwHJLiGA4e6Jrcwq7RfH5nL7ZUHyI_77z43_IQrJYxLbiq_
        GIGYA_DEMO_2=3_7_S7SAvBaZSfIIO9A-kLKFXVzjo3tPUMI0_5KNmAC6tdotjPx8MRy1lxtsfJpcT-
    - if: branch =~ ^release\/([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])).*$
      env:
        ENV=prod

install:
  - yarn

script:
  - if [ "$ENV" != "prod" ]; then scripts/build_demo.sh $ENV $GIGYA_DEMO $GIGYA_DEMO_2; fi
  - if [ "$ENV" = "prod" ]; then sh scripts/prod/build_demo.sh; fi

before_deploy:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv kubectl /usr/local/bin
  - kubectl version --short --client
  - aws eks --region us-east-2 update-kubeconfig --name ownid-eks
  - docker login -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_PASSWORD $ARTIFACTORY_URL

deploy:
  - provider: script
    script: sh scripts/deploy.sh $ENV
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|master)$      
  - provider: script
    script: sh scripts/prod/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^release\/.*$

after_deploy:
  - bash scripts/test_runner.sh demo-site $ENV