sudo: true
notifications:
  slack:
    rooms:
      secure: HmuBbaRMwsLkC305vZCl+I65FBJvFjbATPJOIcwKBb6qp0ZKeol4R05W1WgGw809ARE2FnLZD32IwIO5lS6rEJPGU7eMVTrej9VaPpHEb3z14PxIsTh/pkVg+EZF6tgxpyqJ5+55/KZqz6LsiCdGpehEaAdtqvczFfqaGN46/Gnbjym11IzVqjYdKo6oHNCg5Wpr4Flnx9cLU4kLdPunuKfbmHRyxx1WblXJ4YLKMT1NaUixyOnYqlDRGm/VU3pY5wOA+f+XrqcGuR/TDjAFRe613IcpjRPn5AsNypIoA60CP+DjokSMufRr27FObjo3JhQW6ykKxOurjf8NhV+lvwbVWd+kzuajCsQoTilQYyQXEcj2aaidZIZRSnYK9l07996qcfcQ8/+s6SIX7U3udncousdj81qIcfL9TnyaZnpiqjIYNEsTN3wmfEfVSEXf746tbDD2PBwxQACa7nXzA96uDxO24ou2wdPbo8c2sfsBBlKkhTK98tchqQjdHs1uA+c4+T0XHxUGzQLVRo/ynDXwnb7TVCbuG0OSFRTJvez8ZzMilddZs6dush0/JRclQEQa4l7/50dRLooHcsL7QYCMS2AzU25aEkqGl64uD3djVbHnAATyKVOswDddCwGEvEWG4JzR15gYXFQGvlzopfp7r5nVI9vAMtu2Tc6qf1k=
    on_success: never
    on_failure: always

language: node_js
node_js:
  - '12'

services:
  - docker

cache:
  yarn: true

env:
  global:
    - secure: NDtY1i1VYxMeopm1Dh1EP8Znps/rPgEwNLAwOefoQPB1BbbqZYQA0IjBM5ArDz25MSh5OSFumWb5MBZ71FsKE5oBLjWnAWXqzWj8jiNGfWtsg+DENCXTaPD7pF6YHppWpucodvGi6QAzFaYC7gIG3xrj89kJvAW+DiK7JFxBmvbAMGhI5G/JrOwreTHlbmFjiNj6q+x8R85/GRxB7SOHuwf5kdsylKsFrolyYsDhYe98pH422alH10RSPYJyVler6K3rOLjDlNWxzYPOu4z2V6AV49SG8F/u7gbOuvl9gB9IpwzsWv4O11CmFrz0d3Y/CzF0LBD2NXrD1bq3d+sphir03KOBb9kcm/jPPSk0jlU5B2cDZbOXWRwI3NFYNavPtnscIx2TQwybDdF0snqFD+qWHqnc2JcBqtmdnrYu+wHzreFcrpmdHwfDlJOgQZS2EExief2mux0QkEtdx0bgizb1uOFApYOI44XvKhMwInTculrqwbGDvirPLlNSUDCnveMkkRHtWkMwYenW5GGKwPSwIWsTUQjExuNRlaAEbOp2SyaUcHkmxdb+Jv7HS5HGyxSJ63kV5hmIHO20t5rbs+VqcObAzqXL7ro6S4kwzrpXebY97VgiJhb/Gal86W7AA+eHOf6BKQPYXwL+gurJHwnQeuSb5VvL2TRhVeRxcx4=
    - IMAGE_TAG=$TRAVIS_COMMIT


branches:
  only:
  - master
  - develop

jobs:
  include:
    - if: branch = master
      env: 
        ENV=staging 
        REPOSITORY_URI=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-staging 
        REPOSITORY_DEMO_URI=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-demo-app-staging
        GIGYA_1=3_dEHMimJM2kxcz8gaoI1Sss9kohyJ6LP17qDYd2UIlUfNowsPglEUANJX7R812-uh
        GIGYA_2=3_DS2fdSlSzClFXUfkKHaxJq9-Zknssg2UHamCntjp2jRcL74a_x5HbhDxvHZ6a4q2
        GIGYA_DEMO=3_O4QE0Kk7QstG4VGDPED5omrr8mgbTuf_Gim8V_Y19YDP75m_msuGtNGQz89X0KWP
        GIGYA_DEMO_2=3_uQMbdn-ceccHKTdOmcCqrTDsGq3e7anDWcAxm2g4jFdE63dTpv1S8NCKy_sf_eEA
    - if: branch = develop
      env: 
        ENV=dev 
        REPOSITORY_URI=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-develop 
        REPOSITORY_DEMO_URI=571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-demo-app-develop
        GIGYA_1=3_s5-gLs4aLp5FXluP8HXs7_JN40XWNlbvYWVCCkbNCqlhW6Sm5Z4tXGGsHcSJYD3W
        GIGYA_2=3_2a9se4yNIANdKO12w7Thbs9TKvylPuzZ3HKu4U_Ys6OhNE6aJKwyyGAPFslL0gJr
        GIGYA_DEMO=3_hOdIVleWrXNvjArcZRwHJLiGA4e6Jrcwq7RfH5nL7ZUHyI_77z43_IQrJYxLbiq_
        GIGYA_DEMO_2=3_7_S7SAvBaZSfIIO9A-kLKFXVzjo3tPUMI0_5KNmAC6tdotjPx8MRy1lxtsfJpcT-

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - "$(aws ecr get-login --region us-east-2 --no-include-email)"
  - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv kubectl /usr/local/bin
  - kubectl version --short --client
  - aws eks --region us-east-2 update-kubeconfig --name ownid-eks
  - kubectl -ndev get all

install:
  - yarn

before_script:
  - aws s3 cp s3://cdn.ownid.com/$ENV/js/latest src/assets/ownid-web-ui-sdk --recursive
  - aws s3 cp s3://cdn.ownid.com/$ENV/js/latest projects/demo-app/src/assets/ownid-web-ui-sdk --recursive

script:
#  - yarn test:ci
  - sh scripts/build.sh $ENV $GIGYA_1 $GIGYA_2
  - sh scripts/build_demo.sh $ENV $GIGYA_DEMO $GIGYA_DEMO_2

before_deploy:
  - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv kubectl /usr/local/bin
  - kubectl version --short --client
  - aws eks --region us-east-2 update-kubeconfig --name ownid-eks

deploy:
- provider: script
  script:
    sh scripts/deploy.sh $REPOSITORY_URI $REPOSITORY_DEMO_URI $IMAGE_TAG $ENV
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)$

after_deploy:
  - bash scripts/test_runner.sh demo-site $ENV