apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownid-client-app-deployment
  namespace: dev
  labels:
    app: ownid-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ownid-client-app
  template:
    metadata:
      labels:
        app: ownid-client-app
    spec:
      containers:
        - name: ownid-client-app
          image: 571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-develop:latest
          ports:
            - containerPort: 5002
          env:
            - name: OWNID__WEB_APP_URL
              value: https://sign.dev.ownid.com/sign
            - name: OWNID__CALLBACK_URL
              value: https://client.dev.ownid.com
            - name: OWNID__DID
              value: did:ownid:dev_151850889514
            - name: OWNID__NAME
              value: dev-mozambiquehe.re
            - name: OWNID__DESCRIPTION
              value: DEV environment
            - name: GIGYA__SECRET
              value: g157+kUR3kxvgIX4MneEWnVgBVzhQe4dXfoNe9ceSNA=
            - name: GIGYA__API_KEY
              value: 3_s5-gLs4aLp5FXluP8HXs7_JN40XWNlbvYWVCCkbNCqlhW6Sm5Z4tXGGsHcSJYD3W

---
apiVersion: v1
kind: Service
metadata:
  name: ownid-client-app-service
  namespace: dev
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:571861302935:certificate/c484a4ec-4e6a-408d-b0eb-3c8f1fc1ab68
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: ownid-client-app
  ports:
    - port: 80
      targetPort: 5002
      name: http
    - port: 443
      targetPort: 5002
      name: https
