apiVersion: 'v1'
kind: 'Namespace'
metadata:
  name: 'dev'
  labels:
    name: 'dev'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownid-client-app-deployment
  namespace: dev
  labels:
    app: ownid-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ownid-client-app
  template:
    metadata:
      labels:
        app: ownid-client-app
    spec:
      containers:
        - name: ownid-client-app
          image: 571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-client-app-develop:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ownid-client-app-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: ownid-client-app
  ports:
    - port: 80
      targetPort: 80
