apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownid-client-app-deployment
  namespace: dev
  labels:
    app: ownid-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ownid-client-app
  template:
    metadata:
      labels:
        app: ownid-client-app
    spec:
      containers:
        - name: ownid-client-app
          image: ownid-client-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 5001
              name: https
          env:
            - name: OWNID__WEB_APP_URL
              value: https://sign.dev.ownid.com/sign
            - name: OWNID__CALLBACK_URL
              value: https://client.dev.ownid.com
            - name: OWNID__DID
              value: did:ownid:dev_151850889514
            - name: OWNID__NAME
              value: dev-mozambiquehe.re
            - name: OWNID__DESCRIPTION
              value: DEV environment
            - name: GIGYA__SECRET
              value: g157+kUR3kxvgIX4MneEWnVgBVzhQe4dXfoNe9ceSNA=
            - name: GIGYA__API_KEY
              value: 3_s5-gLs4aLp5FXluP8HXs7_JN40XWNlbvYWVCCkbNCqlhW6Sm5Z4tXGGsHcSJYD3W
            
---
apiVersion: v1
kind: Service
metadata:
  name: ownid-client-app-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: ownid-client-app
  ports:
    - port: 80
      targetPort: 5000
      name: http
    - port: 443
      targetPort: 5001
      name: https